version: '3.8'

services:
  app-production-web:
    image: ghcr.io/seigenta/ggoo:latest
    volumes:
      - /root/git/GGOO/app.logs:/app/app.logs
      - /root/git/GGOO/contributors.json:/app/contributors.json
    env_file:
      - .env
    ports:
      - '9000:3000' # <--- Forzamos el puerto 9000 temporalmente para no tocar tu app activa
    networks:
      - red-swarm-completamente-nueva
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
        monitor: 20s

networks:
  red-swarm-completamente-nueva:
    driver: overlay
    ipam:
      config:
        - subnet: 10.180.0.0/16 # <--- Un rango totalmente nuevo para evitar el "Pool overlap"