allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
minimumReleaseAgeExclude:
  - cookie@0.7.0
  - '@hono/node-server@1.19.13'
