name: Build and Publish Docker Image

# El proceso se activará cada vez que hagas un 'push' a la rama principal (main o master)
on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # Esto transformará el nombre a minúsculas automáticamente para evitar errores de Docker
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Crucial para que GitHub pueda guardar la imagen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Nos logueamos en el GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub genera este token automáticamente

      # Extrae metadatos (como la versión o tags) para la imagen
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      # Construye la imagen y la sube (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # Asegúrate de tener tu Dockerfile en la raíz
          push: true
          tags: ${{ id.meta.outputs.tags }}
          labels: ${{ id.meta.outputs.labels }}