name: Construir y Guardar Imagen Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Construir servicio de producción
        run: |
          docker compose build app-production

      - name: Guardar imagen Docker en archivo TAR
        run: |
          docker save -o app-production.tar ggoo-app-production

      - name: Subir artefacto a GitHub
        uses: actions/upload-artifact@v4
        with:
          name: imagen-produccion-tar
          path: app-production.tar
          retention-days: 7
