name: Prettier Check

on:
    push:
        branches:
            - '**' # Se ejecuta en todas las ramas al hacer push
    pull_request:
        branches:
            - '**' # Se ejecuta en todas las ramas al abrir un PR

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*' # Usa la última versión estable de Node

            - name: Install Dependencies
              run: npm ci # Instalación limpia y rápida para entornos de CI

            - name: Run Prettier Check
              run: npx prettier --check .
