name: Prettier Check

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: 'pnpm'
                  cache-dependency-path: '**/pnpm-lock.yaml' # Asegura encontrar el lockfile

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Prettier Check
              run: pnpm exec prettier --check .
