name: Prettier Check

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'

            # Instalamos pnpm utilizando su opción nativa de caché
            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9
                  dest: ${{ runner.tool_cache }}/pnpm # Asegura una ruta limpia independiente del workspace

            # Si tienes un archivo pnpm-workspace.yaml vacío, este paso previene que rompa la instalación
            - name: Fix potential empty workspace issue
              shell: bash
              run: |
                  if [ -f "pnpm-workspace.yaml" ] && [ ! -s "pnpm-workspace.yaml" ]; then
                    echo "packages:" > pnpm-workspace.yaml
                    echo "  - '*'" >> pnpm-workspace.yaml
                  fi

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Run Prettier Check
              run: pnpm exec prettier --check .
